Add bookings
84R5/java-shareit pull request #2
Opened 2023-05-17 20:18 UTC by 84R5

2023-05-19 19:38 UTC, Donald522 requested changes
Привет!

Помимо комментариев в коде надо разнести классы по пакетам: service / controller и тд

2023-05-19 19:38 UTC, Donald522 commented on src/main/resources/schema.sql
> +    TEXT      VARCHAR(1000)                                       NOT NULL,
По условию задачи нет ограничения на длины текста комментария

2023-05-19 19:38 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingShortDto.java
> +public class BookingShortDto {
Неудачные названия full/ short

Они не дают представления об абстракциях, с которыми работаем

2023-05-19 19:38 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    public static Booking mapToBooking(BookingInputDto bookingInputDto, Booking booking) {
Создавать объект надо полностью внутри маппера, чтобы логика создания не была размазана между разными частями кода

2023-05-19 19:38 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handle(final UnknownStateException e) {
Это скорее 400 должно быть, тк переданное клиентом значение неверно

2023-05-21 16:22 UTC, 84R5 commented
Хотел немного переделать, но пока оставил. В следующем ТЗ буду править )

2023-05-21 18:52 UTC, Donald522 approved these changes
Привет.

Сейчас пойдет.

PS. Работа очень похожа на работу другого студента. Это не очень приветствуется.

2023-05-27 08:44 UTC, merged