Add item requests
84R5/java-shareit pull request #3
Opened 2023-06-08 09:23 UTC by 84R5

2023-06-09 07:55 UTC, 84R5 commented
Тесты ещё пишу... Разбираюсь как нормально протестировать с интерфейсом, и тем что в тестируемом классе едёт вызов другого сервиса ..)

2023-06-09 14:46 UTC, 84R5 commented
Привет, пытаюсь с тестами закончить.. ) Можешь подсказать, как правильно протестировать Service.class, для User получилось. а с другими пока нет. 
java.lang.NullPointerException: Cannot invoke "ru.practicum.shareit.user.service.UserServiceImpl.getUserById(java.lang.Long)" because "this.userServiceImpl" is null
Перечитал теорию, попробовал передать мок, но что то не вышло.

2023-06-10 10:05 UTC, Donald522 requested changes
Привет!

Нужно удалить весь закомменченный код и разобраться почему падает сборка

2023-06-10 10:05 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private String status;
Почему стало String?

2023-06-10 10:05 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +public class CommentDto {
Закомменченный код нужно удалить

2023-06-10 10:05 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoWithDate.java
> +    BookingRequestDto nextBooking;
Тоже

2023-06-10 10:05 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoWithDate.java
> +public class ItemDtoWithDate {
Называется WithDate, а где дата?

2023-06-10 10:19 UTC, 84R5 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoWithDate.java
> +    BookingRequestDto nextBooking;
Да, заметил, когда тесты писал. Когда разбирался с косяком.. понаоставлял, а оказался пустяком.. параметры перепутал)

2023-06-10 10:51 UTC, 84R5 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private String status;
Что бы контроллер уже String отдавал, или не надо?

2023-06-10 10:59 UTC, 84R5 commented
> Привет!
> 
> Нужно удалить весь закомменченный код и разобраться почему падает сборка
Тесты пишу, покрытие нужно больше.. )

2023-06-10 11:41 UTC, 84R5 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoWithDate.java
> +public class ItemDtoWithDate {
Согласен, неудачное название.. Наверно лучше ItemDtoFull, другие в контексте добавления предыдущего и последующего бронирования, звучат странно.

2023-06-12 19:16 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private String status;
В json это в любом случае будет строкой

2023-06-12 19:18 UTC, Donald522 approved these changes

2023-06-12 19:22 UTC, merged